name: Unizer
description: Unizer Mobile

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  firebase_analytics: ^4.0.0
  cloud_firestore: ^0.12.5+2
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  date_format: ^1.0.6
  shared_preferences: ^0.5.3+4
  easy_localization: ^1.2.2+2
  flutter_screenutil: ^0.5.3
  fluttertoast: ^3.1.0
  flutter_html: ^0.10.4
  provider: ^3.0.0+1
  line_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/i18n/en-US.json
    - assets/i18n/nl-NL.json

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf

    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
